server:
  port: 8090
spring:
  application:
    name: 'account-service'
  datasource:
    url: jdbc:postgresql://${ACCOUNT_DB_HOST}:${ACCOUNT_DB_PORT}/${ACCOUNT_DB_SCHEMA}
    username: ${ACCOUNT_DB_USERNAME}
    password: ${ACCOUNT_DB_PWD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  liquibase:
    enabled: true
    url: jdbc:postgresql://${ACCOUNT_DB_HOST}:${ACCOUNT_DB_PORT}/${ACCOUNT_DB_SCHEMA}
    user: ${ACCOUNT_DB_USERNAME}
    password: ${ACCOUNT_DB_PWD}
    change-log: classpath:db/changelog/master.yml
  docker:
    compose:
      file: account-service/compose.yaml
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
jwt:
  refresh-secret: ${REFRESH_SECRET:9UWqDQOYCf0Pe9wtevcZ1AXRBzwpnZN75VySsTmRnrLqz}
  access-secret: ${ACCESS_SECRET:M7Qrp6obpGKnWlbIDA3aVY9oszOCrjAZyAi9PzEFOaUtS}
